spring:
  application:
    name: guicang-backend
  profiles:
    default: sqlite
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

guicang:
  storage:
    root: /home/wb/nas

logging:
  level:
    root: INFO
    com.guicang.nas: DEBUG
